### ISSUE TITLE
Implement the a General RecyclerView List 

### ISSUE THREAD

**Issue by zhpeng811** [CMPUT301F20T21/Book_Friends#29]
Task is to implement the a General RecyclerView List that can be used for the following fragments:
* Your Library - My Books
* Your Library - Borrowed Books
* Borrow - Available Books
* Borrow - Requested Books
* Borrow - Accepted Books

need to wait for the Book entity class and BookService class to be implemented before implementing actual functionalities

Related User Stories:
* [US 01.04.01](https://github.com/CMPUT301F20T21/Book_Friends/wiki/User-Story-(from-eclass)#us-010401)
* [US 06.03.01](https://github.com/CMPUT301F20T21/Book_Friends/wiki/User-Story-(from-eclass)#us-060301)
* [US 04.02.01](https://github.com/CMPUT301F20T21/Book_Friends/wiki/User-Story-(from-eclass)#us-040201)
* [US 05.04.01](https://github.com/CMPUT301F20T21/Book_Friends/wiki/User-Story-(from-eclass)#us-050401)

**Comment by c25vdw** [comment]
I'm currently working on Your Library page, Book entity, and BookService in this branch. Maybe we can make it faster by separate some tasks out. https://github.com/CMPUT301F20T21/Book_Friends/tree/library

**Comment by kdvuong** [comment]
We should definitely separate books entity, service from UI implementation. We want to keep PR small.

**Comment by c25vdw** [comment]
will cut off all my changes in entities and services. we might want to discuss about how a general recycler would work because we have different behaviours on different book list tabs.

**Comment by zhpeng811** [comment]
I thought you were just working on entity and services at the moment. 

Yeah I do agree we should separate the tasks, having a big PR is hard to review

**Comment by zhpeng811** [comment]
Closing this issue since we decide to have one user story per issue
